# Welcome to your law firm website. Change the values in this file to configure your site. 

# The name of your law firm
title: Free Firm Site LLP

# The email address of your law firm. This will be displayed on the website, and messages sent using the contact form will be sent to this address.
email: "info@firm.com"

# The phone number of your law firm. This will be displayed on the website.
phone: "+1 650 391 0000"

# The description of your website. This will be displayed in the footer of the website
description: >- # this means to ignore newlines until "baseurl:"
  Law Firm is the leading full-service firm in the San Francisco Bay Area. No matter your issue, we have your covered.

#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# The tagline of your website. This will be displayed on the home page of your website
tagline: Experienced, Flexible, Effective

# The secondary tagline of your website. This will be displayed on the home page of your website, under the primary tagline
secondary_tagline: We are the leading full-service firm in the San Francisco Bay Area.

# The url of the main image of your website. This image is displayed front and center on the home page. 
background_image: https://images.unsplash.com/photo-1422226256160-9b266e308ea6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2853&q=80

repository: "nicolas-van/bootstrap-4-github-pages"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  - posts

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
