- name: Estate Planning Services
  description: >
    Depending on your assets and goals, your estate plan may include:
    <ul>
    <li>Wills</li>
    <li>Trusts</li>
    <li>Probate</li>
    <li>Statutory Durable Powers of Attorney</li>
    <li>Medical Powers of Attorney</li>
    <li>Guardianship Designations</li>
    <li>Advance Directives</li>
    </ul>

- name: Probate Services
  description: >
    <ul>
    <li>Probate of Wills</li>
    <li>Affadavits of Heirship</li>
    <li>Heirships</li>
    </ul>
