- name: Estate Planning Services
  description: Depending on your assets and goals, your estate plan may include: Wills, Trusts, Statutory Durable Powers of Attorney, Medical Powers of Attorney, Guardianship Designations, Advance Directives
